### ISSUE TITLE
Doesn't work in python 3.4

### ISSUE THREAD

**Issue by dmitriyshashkin** [larrabee/ewn#3]
ewn -c "exit 2"

```
Traceback (most recent call last):
  File "/usr/bin/ewn", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/ewn/__init__.py", line 110, in main
    RunFile().create()
  File "/usr/lib/python3.4/site-packages/ewn/__init__.py", line 42, in __init__
    self.file_name = hashlib.sha1(cli.command).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```
can be fixed quite easily though:
`self.file_name = hashlib.sha1(cli.command.encode('utf-8')).hexdigest()`

**Comment by larrabee** [comment]
Hello. This version no longer supported. You can use [https://github.com/larrabee/ewn-go](ewn-go), its same program written on golang.
